Using device: cuda
Scattering Flare Image: Flare7K  is loaded successfully with  5000  flares
Scattering Flare Image: Flare7K  is loaded successfully with  5000  flares
Traceback (most recent call last):
  File "/home/nieb/Projects/DAKI Projects/P3/Modules/train.py", line 163, in <module>
    train(model_name, optimizer_name, preprocessing_name, preprocessing_size, dataset_name, output_path, loss, batch_size)
  File "/home/nieb/Projects/DAKI Projects/P3/Modules/train.py", line 70, in train
    outputs = model(inputs)
              ^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/Projects/DAKI Projects/P3/Models/model_zoo/U_Net.py", line 118, in forward
    d3 = self.Up3(d4)
         ^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/Projects/DAKI Projects/P3/Models/model_zoo/U_Net.py", line 36, in forward
    x = self.up(x)
        ^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/modules/upsampling.py", line 172, in forward
    return F.interpolate(
           ^^^^^^^^^^^^^^
  File "/home/nieb/.conda/envs/UNI/lib/python3.11/site-packages/torch/nn/functional.py", line 4536, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 3.71 GiB of which 80.56 MiB is free. Process 8747 has 22.22 MiB memory in use. Including non-PyTorch memory, this process has 3.57 GiB memory in use. Of the allocated memory 3.38 GiB is allocated by PyTorch, and 116.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
